const DemoData = {
  viewerData: {
    yamadaneko0: {
      nickname: "山田ねこ",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "yamadaneko0",
      userId: "6519198320958439426",
      followRole: 2,
    },
    ginchan398: {
      nickname: "ぎんちゃん",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "ginchan398",
      userId: "6923219831643096065",
      followRole: 0,
    },
    "s.yoshida_1972": {
      nickname: "吉田重博@からあげ@しげたん",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "s.yoshida_1972",
      userId: "6918412779691557890",
      followRole: 2,
    },
    "mikan.0219": {
      nickname: "ミカン0219😘🍡",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "mikan.0219",
      userId: "7077075276946031617",
      followRole: 2,
    },
    "my.bodrum": {
      nickname: "My.Bodrum",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "my.bodrum",
      userId: "7088785813484635137",
      followRole: 1,
    },
    rvf400186: {
      nickname: "RVFchoro😚🍡",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "rvf400186",
      userId: "7072674179162309634",
      followRole: 2,
    },
    chausieuvi41korena: {
      nickname: "CHÂU SIÊU VI",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "chausieuvi41korena",
      userId: "7094895261764731905",
      followRole: 1,
    },
    mitsuka26: {
      nickname: "❤️❄️ 佳ちゃん🌸😘🍡❤️",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "mitsuka26",
      userId: "6877025271611933698",
      followRole: 2,
    },
    accnhatnek04: {
      nickname: "accnhatnek04",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "accnhatnek04",
      userId: "7131149128894202882",
      followRole: 1,
    },
    cvh_nitsaoduoc: {
      nickname: "Tik Toker",
      profilePictureUrl: window.defaultAvatar,
      uniqueId: "cvh_nitsaoduoc",
      userId: "7082485754844431362",
      followRole: 0,
    },
  },
  viewerPoint: {
    yamadaneko0: 287,
    ginchan398: 27,
    "s.yoshida_1972": 303,
    "mikan.0219": 45,
    "my.bodrum": 1,
    rvf400186: 492,
    chausieuvi41korena: 7,
    mitsuka26: 11,
    accnhatnek04: 26,
    cvh_nitsaoduoc: 1,
  },
  lastEvents: [
    {
      likeCount: 24,
      totalLikeCount: 30628,
      userId: "7131149128894202882",
      secUid:
        "MS4wLjABAAAAxIPVf24-o27HPVfIA4_mf4gKq_CWa6BPaOM1uvjDrRZ5Mk6I1WLs3uVhWf615VEp",
      uniqueId: "accnhatnek04",
      nickname: "accnhatnek04",
      profilePictureUrl: window.defaultAvatar,
      followRole: 1,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 74,
        followerCount: 8,
        followStatus: 1,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860701100264194",
      createTime: "1664008177864",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "GuJXURxNjF",
    },
    {
      likeCount: 1,
      totalLikeCount: 30619,
      userId: "7082485754844431362",
      secUid:
        "MS4wLjABAAAAoV1DCLb27dKtD0NaYIq_2k2h0XXW72jhTgmRM3GpIV3gg-nK_y6QNBVCfVgR3cqy",
      uniqueId: "cvh_nitsaoduoc",
      nickname: "Tik Toker",
      profilePictureUrl: window.defaultAvatar,
      followRole: 0,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 104,
        followerCount: 72,
        followStatus: 0,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860687892417281",
      createTime: "1664008174913",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "KrMhQ5UmTJ",
    },
    {
      likeCount: 2,
      totalLikeCount: 30564,
      userId: "7131149128894202882",
      secUid:
        "MS4wLjABAAAAxIPVf24-o27HPVfIA4_mf4gKq_CWa6BPaOM1uvjDrRZ5Mk6I1WLs3uVhWf615VEp",
      uniqueId: "accnhatnek04",
      nickname: "accnhatnek04",
      profilePictureUrl: window.defaultAvatar,
      followRole: 1,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 74,
        followerCount: 8,
        followStatus: 1,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860559525219074",
      createTime: "1664008144747",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "GhfrD41w7R",
    },
    {
      likeCount: 6,
      totalLikeCount: 30562,
      userId: "6877025271611933698",
      secUid:
        "MS4wLjABAAAA2x3oiqlSOTPuiHsVx-pdBi9bo37rmnyTyE-HpN8iEOpvoBWuLuZ_5PYp4vuel8Fw",
      uniqueId: "mitsuka26",
      nickname: "❤️❄️ 佳ちゃん🌸😘🍡❤️",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [
        {
          badgeSceneType: 1,
          type: "pm_mt_moderator_im",
          name: "Moderator",
        },
        {
          type: "image",
          badgeSceneType: 4,
          displayType: 1,
          url: "https://p19-webcast.tiktokcdn.com/webcast-sg/22172b1ad88bc7dea93acd16c5bc7c76~tplv-obj.image",
        },
        {
          type: "image",
          badgeSceneType: 6,
          displayType: 1,
          url: "https://p19-webcast.tiktokcdn.com/webcast-va/ranklist_top_gifter_1.png~tplv-obj.image",
        },
      ],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 129,
        followerCount: 634,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: true,
      isNewGifter: false,
      isSubscriber: true,
      topGifterRank: 1,
      msgId: "7146860394689792794",
      createTime: "1664008106696",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "PDre0H6Tt3",
    },
    {
      likeCount: 5,
      totalLikeCount: 30556,
      userId: "6877025271611933698",
      secUid:
        "MS4wLjABAAAA2x3oiqlSOTPuiHsVx-pdBi9bo37rmnyTyE-HpN8iEOpvoBWuLuZ_5PYp4vuel8Fw",
      uniqueId: "mitsuka26",
      nickname: "❤️❄️ 佳ちゃん🌸😘🍡❤️",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [
        {
          badgeSceneType: 1,
          type: "pm_mt_moderator_im",
          name: "Moderator",
        },
        {
          type: "image",
          badgeSceneType: 4,
          displayType: 1,
          url: "https://p19-webcast.tiktokcdn.com/webcast-sg/22172b1ad88bc7dea93acd16c5bc7c76~tplv-obj.image",
        },
        {
          type: "image",
          badgeSceneType: 6,
          displayType: 1,
          url: "https://p19-webcast.tiktokcdn.com/webcast-va/ranklist_top_gifter_1.png~tplv-obj.image",
        },
      ],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 129,
        followerCount: 634,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: true,
      isNewGifter: false,
      isSubscriber: true,
      topGifterRank: 1,
      msgId: "7146860361802451739",
      createTime: "1664008099125",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "yjszHFFewC",
    },
    {
      likeCount: 112,
      totalLikeCount: 30551,
      userId: "6918412779691557890",
      secUid:
        "MS4wLjABAAAAwyeUL0g0nd0n9LbC1EcaEG0JRngTMf4f6_xMoi6b8dLd8bEo3M8wWluhpEh2X9kV",
      uniqueId: "s.yoshida_1972",
      nickname: "吉田重博@からあげ@しげたん",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 57,
        followerCount: 162,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860348749253378",
      createTime: "1664008095839",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "NDwCNIr5Ht",
    },
    {
      likeCount: 7,
      totalLikeCount: 30484,
      userId: "7094895261764731905",
      secUid:
        "MS4wLjABAAAAbdBaZCJabE0kPuKy6vHKv6a4SkhEViSJqNcZKiF4vXy0xvhllTczEi3OqbjThQD9",
      uniqueId: "chausieuvi41korena",
      nickname: "CHÂU SIÊU VI",
      profilePictureUrl: window.defaultAvatar,
      followRole: 1,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 554,
        followerCount: 186,
        followStatus: 1,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860291941665537",
      createTime: "1664008082841",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "O2aDpL0nAO",
    },
    {
      likeCount: 492,
      totalLikeCount: 30432,
      userId: "7072674179162309634",
      secUid:
        "MS4wLjABAAAAzTudhh-366KRl5HQYXZveyYGmpAZkU5p2oMIb9O63M96l1gLoFMhHPqR8quLy_Kh",
      uniqueId: "rvf400186",
      nickname: "RVFchoro😚🍡",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [
        {
          badgeSceneType: 1,
          type: "pm_mt_moderator_im",
          name: "Moderator",
        },
        {
          type: "image",
          badgeSceneType: 4,
          displayType: 1,
          url: "https://p19-webcast.tiktokcdn.com/webcast-sg/768d1d6c72708df6d93a5bf3e06e585b~tplv-obj.image",
        },
      ],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 417,
        followerCount: 363,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: true,
      isNewGifter: false,
      isSubscriber: true,
      topGifterRank: null,
      msgId: "7146860156112898817",
      createTime: "1664008051000",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "XXvJ0kKJbs",
    },
    {
      likeCount: 75,
      totalLikeCount: 30390,
      userId: "6519198320958439426",
      secUid:
        "MS4wLjABAAAAwUWlarUIP6Ao2myOLAjZo2chMokRsfi4s6m3TPd5dccD9TBYjIT3l_wHak85hEhh",
      uniqueId: "yamadaneko0",
      nickname: "山田ねこ",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 1410,
        followerCount: 1391,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860117189905153",
      createTime: "1664008041752",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "oS212S3dnH",
    },
    {
      likeCount: 1,
      totalLikeCount: 30225,
      userId: "7088785813484635137",
      secUid:
        "MS4wLjABAAAASVXBDdwNtmGiHnsK_S4RpXhOvo_K0ve5KSzMerk2dOMqdX4gJzWN275hYJuOr1sa",
      uniqueId: "my.bodrum",
      nickname: "My.Bodrum",
      profilePictureUrl: window.defaultAvatar,
      followRole: 1,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 560,
        followerCount: 142,
        followStatus: 1,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860037134240513",
      createTime: "1664008023260",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "aUJgK9cBfc",
    },
    {
      likeCount: 53,
      totalLikeCount: 30209,
      userId: "6519198320958439426",
      secUid:
        "MS4wLjABAAAAwUWlarUIP6Ao2myOLAjZo2chMokRsfi4s6m3TPd5dccD9TBYjIT3l_wHak85hEhh",
      uniqueId: "yamadaneko0",
      nickname: "山田ねこ",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 1410,
        followerCount: 1391,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146860025926273793",
      createTime: "1664008020686",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "Z0ph8Xhkjx",
    },
    {
      likeCount: 45,
      totalLikeCount: 30066,
      userId: "7077075276946031617",
      secUid:
        "MS4wLjABAAAAWvP-iQzD9N2rCHSLGbDVkurublhU3LC5ncW4DyFO82cMnJNlxpSEITWEyvygsXeG",
      uniqueId: "mikan.0219",
      nickname: "ミカン0219😘🍡",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [
        {
          badgeSceneType: 1,
          type: "pm_mt_moderator_im",
          name: "Moderator",
        },
        {
          type: "image",
          badgeSceneType: 4,
          displayType: 1,
          url: "https://p19-webcast.tiktokcdn.com/webcast-sg/5cfee85102543f29229064a753624ad1~tplv-obj.image",
        },
      ],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 537,
        followerCount: 79,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: true,
      isNewGifter: false,
      isSubscriber: true,
      topGifterRank: null,
      msgId: "7146859947695180545",
      createTime: "1664008002512",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "RWADpU8p7Y",
    },
    {
      likeCount: 25,
      totalLikeCount: 30006,
      userId: "6519198320958439426",
      secUid:
        "MS4wLjABAAAAwUWlarUIP6Ao2myOLAjZo2chMokRsfi4s6m3TPd5dccD9TBYjIT3l_wHak85hEhh",
      uniqueId: "yamadaneko0",
      nickname: "山田ねこ",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 1410,
        followerCount: 1391,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146859926152153857",
      createTime: "1664007997479",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "aQ0YYb02Cg",
    },
    {
      likeCount: 191,
      totalLikeCount: 29921,
      userId: "6918412779691557890",
      secUid:
        "MS4wLjABAAAAwyeUL0g0nd0n9LbC1EcaEG0JRngTMf4f6_xMoi6b8dLd8bEo3M8wWluhpEh2X9kV",
      uniqueId: "s.yoshida_1972",
      nickname: "吉田重博@からあげ@しげたん",
      profilePictureUrl: window.defaultAvatar,
      followRole: 2,
      userBadges: [],
      userDetails: {
        createTime: "0",
        bioDescription: "",
        profilePictureUrls: [
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
          window.defaultAvatar,
        ],
      },
      followInfo: {
        followingCount: 57,
        followerCount: 162,
        followStatus: 2,
        pushStatus: 0,
      },
      isModerator: false,
      isNewGifter: false,
      isSubscriber: false,
      topGifterRank: null,
      msgId: "7146859890018224897",
      createTime: "1664007989113",
      displayType: "pm_mt_msg_viewer",
      label: "{0:user} liked the LIVE",
      name: "like",
      id: "3trOKSMGiB",
    },
  ],
  topRanking: [
    "rvf400186",
    "s.yoshida_1972",
    "yamadaneko0",
    "mikan.0219",
    "ginchan398",
    "accnhatnek04",
    "mitsuka26",
    "chausieuvi41korena",
    "my.bodrum",
    "cvh_nitsaoduoc",
  ],
}
export default DemoData
